apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: aetibqg7bi800d    # 👈 This UID must match the one in dashboards.yml
    url: http://172.17.0.1:9090
    isDefault: true
    editable: true
