[smtp]
enabled = true
host = smtp.gmail.com:587
user = goyalankitgoyal32@gmail.com
password = twbm zsjg sjnk jtdk
  ; NOT your real Gmail password
; Use app-specific password if 2FA is enabled

from_address = goyalankitgoyal32@gmail.com
from_name = Grafana Alerts
skip_verify = true
